version: 0.2
phases:
  build:
    commands:
      - pip install --upgrade pip
      - pip install pipenv --user
      - pipenv install aws-sam-cli
      - export BUCKET=charles-send-email-artifacts-1
      - sam package --template-file template.yml --output-template-file packaged-template.yml --s3-bucket $BUCKET
artifacts:
  files:
    - packaged-template.yml
