version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - pip install --upgrade pip
      - pip install pipenv --user
      - pipenv install awscli aws-sam-cli
      - export BUCKET=charles-send-email-artifacts-1
      - pipenv run sam package --template-file template.yml --output-template-file packaged-template.yml --s3-bucket $BUCKET
artifacts:
  files:
    - packaged-template.yml
