AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  SendEmailToSubscriptionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Events:
        SendEmailApi:
          Type: Api
          Properties:
            Path: /
            Method: GET
      Policies:
      - SNSPublishMessagePolicy:
          TopicName:
            Fn::GetAtt:
            - SendEmailSnsTopic
            - TopicName
      Environment:
        Variables:
          SNS_TOPIC_ARN:
            Ref: SendEmailSnsTopic
      CodeUri: s3://charles-send-email/48bcb4aa12033a5aa64acdd0e5557590
  SendEmailCharlesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.sendEmail
      Runtime: nodejs8.10
      Events:
        SendEmailApi:
          Type: Api
          Properties:
            Path: /sendEmail
            Method: GET
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - ses:SendEmail
          - ses:SendRawEmail
          Resource: '*'
      CodeUri: s3://charles-send-email/48bcb4aa12033a5aa64acdd0e5557590
  SendEmailSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint: cpobre@treatanyone.com
        Protocol: email
